const subjects = [
  'Life',
  'Love',
  'Relationships',
  'Work',
  'Learning',
  'Adventure',
  'Growth',
  'Nature',
  'Dreams',
  'Change',
  'Success',
  'Journey',
  'Creativity',
  'Art',
  'Challenges',
  'Travel',
  'Happiness',
  'Emotions',
  'Memory',
  'Friendship',
  'Health',
  'Family',
  'Exploration',
  'Dreams',
  'Time',
  'Struggle',
  'Freedom',
  'Strength',
  'Mindset',
  'Experience',
  'The Future',
  'Imagination',
  'The World',
  'Passion',
  'Self-discovery',
  'Opportunities',
  'The Unknown',
  'Growth',
  'Reflection',
  'Purpose',
  'Peace',
  'Courage',
  'Joy',
  'Hope',
  'Learning',
  'Connection',
  'The Universe',
  'Nature',
  'Wisdom',
];

const adjectives = [
  'adventurous',
  'beautiful',
  'challenging',
  'chaotic',
  'colorful',
  'complicated',
  'confusing',
  'dynamic',
  'evolving',
  'exciting',
  'fleeting',
  'fragile',
  'frustrating',
  'fulfilling',
  'harmonious',
  'inspiring',
  'intense',
  'intriguing',
  'joyful',
  'liberating',
  'magical',
  'meaningful',
  'messy',
  'mysterious',
  'painful',
  'passionate',
  'peaceful',
  'perplexing',
  'precious',
  'purposeful',
  'radiant',
  'refreshing',
  'rewarding',
  'rich',
  'rough',
  'satisfying',
  'serene',
  'simple',
  'surprising',
  'sweet',
  'temporary',
  'tender',
  'uncertain',
  'unpredictable',
  'unstable',
  'uplifting',
  'vibrant',
  'vulnerable',
  'wondrous',
];

export function thingsAre(element) {
  const setThings = () => {
    let thing = subjects[random(subjects)];
    let is = adjectives[random(adjectives)];
    element.innerHTML = `${thing} ${/[^s]s$/.test(thing) ? 'are' : 'is'} ${is}`;
  };
  const random = (element) => Math.floor(Math.random() * element.length);
  element.addEventListener('click', () => setThings());
  setThings();
}
